<a href="https://colab.research.google.com/github/eolmez91/Study-Notes-Kodluyoruz-BOOTCAMP/blob/master/05_05_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#############-----------NumPy------------##############

In [0]:
"""
Scalar: tek bir değer 1,3,4...
Vector: Yönü ve şiddeti belli 3.0, -1.5
Matris: 2 Boyutlu veriler Matrisler
Tensor: 3 Boyutlu veriler
"""


'\nScalar: tek bir değer 1,3,4...\nVector: Yönü ve şiddeti belli 3.0, -1.5\nMatris: 2 Boyutlu veriler Matrisler\nTensor: 3 Boyutlu veriler\n'

In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3]) # Birinci dereceden dizi tanımlayalaım

print(type(a))          # Dizinin veri tiğini yazdıralım
print(a.shape)          # Dizinin şeklini yazdıralım
print(a.ndim)           # Dizinin boyutunu yazdıralım
print(a[0], a[1], a[2]) # Dizinin her bir elemanı ayrı ayrı yazdıralım
a[0] = 5                # Dizinin ilk elamanını 5 ile değiştirelim
print(a)

<class 'numpy.ndarray'>
(3,)
1
1 2 3
[5 2 3]


In [0]:
b = np.array([[1,2,3], [4,5,6]]) # İkinci dereceden dizi tanımlayalım

print(b)
print(b.ndim)
print(b.shape)
print(b[0, 0], b[0,1], b[1,0])


[[1 2 3]
 [4 5 6]]
2
(2, 3)
[0, 0] 2 4


In [0]:
c = np.array([[[1,2,3], [4,5,6], [7,8,9]]]) 

print(c)
print(c.ndim)
print(c.shape)
print(c[0,1,0])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)
4


In [0]:
a = np.zeros((2,2,)) # Tüm elemanları "sıfır" olan 2 x 2 boyutlu dizi
print(a)

b = np.ones((1,2))   # Tün elemanları "bir" olan 1x2 boyutlu dizi
print(b)

c = np.full((2,2,), 7) # Tüm elemanları "yedi" olan 2x2 boyutlu dizi
print(c)

d = np.empty((4,5))
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1.93446700e-316 2.33419537e-312 8.48798317e-313 2.56761491e-312
  2.14321575e-312]
 [2.07955588e-312 1.01855798e-312 6.79038653e-313 1.97345609e-312
  6.79038653e-313]
 [1.93101617e-312 9.33678148e-313 1.97345609e-312 6.79038653e-313
  1.93101617e-312]
 [9.33678148e-313 1.97345609e-312 8.70018274e-313 2.27462358e-307
  1.36621061e+161]]


In [0]:
e = np.eye(4)      # 2 x 2 boyutlu birim matris
print(e)

f = np.random.random((5,5))  # 5 x 5 boyutlu rastgele değerlerden oluşan matris
print(f)

g = np.arange(0,10,1) # 0'dan 10'a (hariç) aralarına 1 olan
print(g)

h = np.linspace(0,9,10) # 0'dan 9'a (dahil) 10 adet sayı
print(h)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.21625562 0.89223982 0.58296445 0.88929313 0.83207022]
 [0.66034205 0.37113799 0.57703591 0.50012762 0.86292683]
 [0.27682684 0.42274781 0.44770721 0.0724699  0.17570322]
 [0.61123827 0.17731105 0.27018867 0.43633884 0.99584457]
 [0.05240526 0.51883283 0.89153374 0.22813118 0.40417438]]
[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [0]:
print(np.random.randint(1))
print(np.random.randint(10))
print(np.random.randint(5,10))
print(np.random.randint(5,10, size = 10))
print(np.random.randint(5,10, size = (5,4)))

0
4
5
[7 6 9 5 9 5 9 7 8 5]
[[9 7 5 5]
 [7 9 8 7]
 [6 7 7 8]
 [9 6 8 8]
 [5 8 9 9]]


In [0]:
print(np.random.rand(10))
print(np.random.rand(5,10))

print(np.random.randn(10))
print(np.random.randn(5,10))

[0.57161202 0.86901623 0.82136159 0.40886756 0.10703534 0.64871298
 0.94248739 0.78497866 0.1257119  0.85771876]
[[0.76663251 0.20720024 0.11313308 0.04435921 0.40107121 0.06875536
  0.73761525 0.9644321  0.61300518 0.51534948]
 [0.45074321 0.48532151 0.82008651 0.6910482  0.03813354 0.46696109
  0.40069673 0.33024996 0.67392228 0.98461217]
 [0.80860585 0.80454659 0.76878583 0.7494902  0.63853717 0.0250091
  0.1098959  0.21795556 0.91219458 0.44734853]
 [0.27619466 0.74602259 0.99713059 0.36603847 0.56945846 0.31788041
  0.44818972 0.18844283 0.79127225 0.23216115]
 [0.50548284 0.18116412 0.84553667 0.51698211 0.53243467 0.33658289
  0.07638843 0.18651821 0.77802364 0.30102811]]
[ 1.36060893 -0.08656412 -0.04316986  1.30094275  1.31795638 -0.53610413
 -0.60655309 -0.55406488  1.11979631  1.34284396]
[[-3.60029347e-01  6.34815386e-03 -6.19467287e-03  3.89417032e-01
   1.56741251e+00  2.07690172e-01 -7.11134393e-01  1.49487230e+00
   4.56279436e-01  1.02597018e+00]
 [-2.86471285e-01  9.6

In [0]:
dizim = np.array([11,22,23,14,5,36,7,3,9,5,11,133,13,5,66])

dizim.shape

dizim.reshape(5,3)

NameError: ignored

In [0]:
dizim.resize(5,3)
print(dizim)

[[ 11  22  23]
 [ 14   5  36]
 [  7   3   9]
 [  5  11 133]
 [ 13   5  66]]


In [0]:
# Dizilerde temel işlemler

In [0]:
dizim = dizim.ravel()

print(dizim)

print(dizim.size)

print(dizim.dtype) # elemanların veri tipini gösterir

print(dizim.max())

print(dizim.min())

dizim[::-1]

[ 11  22  23  14   5  36   7   3   9   5  11 133  13   5  66]
15
int64
133
3


array([ 66,   5,  13, 133,  11,   5,   9,   3,   7,  36,   5,  14,  23,
        22,  11])

In [0]:
# Arkaarkaya "::" Baştan başla sona kadar git.

In [0]:
yeni = np.random.randint(1,100,10)

print(yeni)

print(yeni.argmax()) # Maksimum indeks değeri

print(yeni.argmin()) # Minimum indeks değeri

print(yeni.mean())   # Ortalamalarını alır


[44 81 47 13 33 19 98 48 58 87]
6
3
52.8


In [0]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

np.vstack((a,b)) # vertical (dikey) birleştirme, alt alta ekler

np.hstack((a,b)) # horizantal (yatay) birleştirme, yan yana ekler

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [0]:
dizi = np.array([0,1,2,3,4,5,6,7,8,9,]).reshape(5,2)

# Diziyi yazdıralım
print("Orjinal")
print(dizi)

# Satır bazlı birleştirme
print("Satır bazlı birleştirilmiş")
print(np.concatenate([dizi, dizi], axis = 0))

# Sütun bazlı birleştirme
print("Sütun bazlı birleştirme")
print(np.concatenate([dizi, dizi], axis = 1))

Orjinal
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Satır bazlı birleştirilmiş
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Sütun bazlı birleştirme
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]
 [8 9 8 9]]


In [0]:
# Dizilerde Dilimleme (Slicing)

a = np.array([[1,2,3,4],
              [5,6,7,8],
             [9,10,11,12]])

b = a[:2, 1:3]   # 0. ve 1.satır / 1. ve 2. sütun

print(b)

[[2 3]
 [6 7]]


In [0]:
print(a[0,1])

b[0, 0] = 77 # b[0,0] ile aslında a[0,1]'yı işaret ediypurz

print (a[0,1]) # değişmesini istemiyorsak b = a.copy()

2
77


In [0]:
satir_v1 = a[1, :]   # İkinci satırın 1. dereceden görünüşü
satir_v2 = a[1:2, :] # İkinci satırın 2. dereceden görünüşü
satir_v3 = a[[1], :] # İkinci satırın 3. dereceden görünüşü

print(satir_v1, satir_v1.shape)
print(satir_v2, satir_v2.shape)
print(satir_v3, satir_v3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [0]:
sutun_v1 = a[:, 1]
sutun_v2 = a[:, 1:2]

print(sutun_v1, sutun_v1.shape) # 1. derece
print(sutun_v2, sutun_v2.shape) # 2. derece

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [0]:
a = np.array([[1,2], [3,4], [5,6]])

# a[0,0], a[1,1] ve a[2,0]'ı indekslemek için
print(a[[0,1,2], [0,1, 0]])

# Ayrı ayrı indeksleme yapalım
print(np.array([a[0,0], a[1,1], a[2,0]]))

[1 4 5]
[1 4 5]


In [0]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a)

# İndis dizisi oluşturalım
indis = np.array([0, 2, 0, 1])

# Her satırdan sırasıyla indis dizisini kullanarak değerleri seçelim
print(a[np.arange(4), indis]) # "[1 6 7 11]"

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]


In [0]:
# İndis dizisini kullanarak elemanlara 10 ekleyelim
a[np.arange(4), indis] += 10

print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [0]:
# sigmoid fonksiyonu tanımlama ÖDEV