<a href="https://colab.research.google.com/github/eolmez91/Study-Notes-Kodluyoruz-BOOTCAMP/blob/master/12_05_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a = np.array([[1,2], [3,4], [5,6]])

print(a)



[[1 2]
 [3 4]
 [5 6]]


In [0]:
ikidenBuyuk = (a>2) # 2'den büyük olanları seçelim
                    # a dizisi ile aynı boyutta yeni boyun oluşturur
                    # 2'den büyük ise True, küçük ise False döndürür
    
print(ikidenBuyuk)

[[False False]
 [ True  True]
 [ True  True]]


In [0]:
# Boolean indekseleme kullanarak bulduğumuz değerleri yazdıralım
print(a[ikidenBuyuk])

# 2'den büyüj olanları şu şekilde de bulabiliriz.

print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


In [0]:
x = np.array([1,2])          # Veri tipini Numpy seçsin
y = np.array([1.0, 2.0])  # Veri tiğini Numpy seçsin
z = np.array([1,2], dtype=np.int64) # Veri tiğini BİZ belirleyelim

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [0]:
#Numpy Dizilerde Matematiksel İşlemler

In [0]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

print(x + y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [0]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [0]:
print(x*y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [0]:

print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]


In [0]:
x = np.array([[4,9], [16,81]], dtype = np.float64)

print(np.sqrt(x))
print(np.square(x))
print(np.exp(x))
print(np.exp(1)) # E sayısının değeri

[[2. 3.]
 [4. 9.]]
[[  16.   81.]
 [ 256. 6561.]]
[[5.45981500e+01 8.10308393e+03]
 [8.88611052e+06 1.50609731e+35]]
2.718281828459045


In [0]:
buyuk_sayilar = np.array([10, 100, 1000, 10000, 100000, 10000000000000])

print(np.log(buyuk_sayilar))

[ 2.30258509  4.60517019  6.90775528  9.21034037 11.51292546 29.93360621]


In [0]:
# Dizilerde Sinüs Bulma

In [0]:
x = np.array([np.pi/6, np.pi/2, np.pi/3])

print(np.sin(x))

[0.5       1.        0.8660254]


In [0]:
# Dizi elelmanlarını toplama

In [0]:
x = np.array([[1,2], [3,4]])

print(np.sum(x))           # Tüm matris elemanlarının toplamını ekrana yazdırır
print(np.sum(x, axis = 0)) # Sütün toplamlarını ekrana yazdırır
print(np.sum(x, axis = 1)) # Satır toplamlarını ekrana yazdırır

10
[4 6]
[3 7]


In [0]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [0]:
v = np.array([[1,2,3]])

print(v.T)

[[1]
 [2]
 [3]]


In [0]:
y = np.array([1,2,3,4])

print(y.shape)

y.T

print(y.shape)

(4,)
(4,)


In [0]:
# v vektörünü x matrsinin her bir satırına eklemek isteyelim
# sonuçları y matrisinde tutalım

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # x ile aynı boyuta sahip bir matris oluşturalım

print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [0]:
# ve vektörünü x matrisinin her bir satırına for döngüsü kullanarak ekleme

for i in range(4):
  y[i, :] = x[i, :] + v
  
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [0]:
vv = np.tile(v, (4, 1)) # 4 satırda 1'er kere v vektörünü kullanma

print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [0]:
y = x + vv

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [0]:
# y vektörünü x matrisinin her bir saturuna eklemek isteyelim
# sonuçları ye matrisinde tutalım

y = (x + v) # x matrisinin her satırına v vektörünü broadcasting kullanarak ekleyelim

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [0]:
# v ile w'nin vektörel çarpımını hesaplayalım

v = np.array([1,2,3]) # v'nin boyutu (3,)
w= np.array([4,5])    # w'nin boyutu (2,)

print(np.reshape(v, (3,1))* w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [0]:
# PÜF NOKTALAR
a = np.array([0])
b = 0

print(a/a)
print(b/b)

[nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


ZeroDivisionError: ignored

In [0]:
x = np.array([1, 2, 2.5])

print(x)

x = x.astype(int)

print(x)

[1.  2.  2.5]
[1 2 2]


In [0]:
x = np.array([1, 2])

print(x.shape)
x=np.expand_dims(x, axis=0)
print(x.shape)
x=np.expand_dims(x, axis=0)
print(x.shape)
x=np.expand_dims(x, axis=0)
print(x.shape)

(2,)
(1, 2)
(1, 1, 2)
(1, 1, 1, 2)


In [0]:
x=np.expand_dims(x, axis=1)
print(x.shape)
x=np.expand_dims(x, axis=1)
print(x.shape)
x=np.expand_dims(x, axis=1)
print(x.shape)

(1, 1, 1, 1, 2)
(1, 1, 1, 1, 1, 2)
(1, 1, 1, 1, 1, 1, 2)


In [0]:
# Numpy is over

In [0]:
# yapay sinir ağında beklenen sonuç çıkmadığında hata payını ölçmek için kullanılan "cost function" kullanılmaıldır. 1/2(hedeflenen-tahmin)**2 
# ETotal = toplam1/2(hedeflenen-tahmin)**2
# parametre yapay sinir ağımın kendi kendine öğrendiği değerlere denir homerwork 6'da 10 tane parametre var w ve b'ler
# zincir türev alma
# 1. o1- hedeflenen 2. o1(1-o1) 3. out h1
#etotal/w5 = (etotal/o1)(o1/out h1)( out h1/w5)

#hatayı hesaplay
#learning rate